### ISSUE TITLE
Add license text

### ISSUE THREAD

**Issue by chrismay2** [maydesk/modules#1]
Add the Mozilla licence boiler plate to each Java file:

/*
- This file is part of the Echo Point Project.  This project is a
- collection of Components that have extended the Echo Web Application
- Framework Version 3.
  *
- Version: MPL 1.1
  *
- The contents of this file are subject to the Mozilla Public License Version
- 1.1 (the "License"); you may not use this file except in compliance with
- the License. You may obtain a copy of the License at
- http://www.mozilla.org/MPL/
  *
- Software distributed under the License is distributed on an "AS IS" basis,
- WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
- for the specific language governing rights and limitations under the
- License.
  */

**Comment by kriegerd** [comment]
Should I remove the old PROFIDESK license? 
Looking at the MPL site and what you posted above I think it should go something like this: 

``` java
/* This file is part of the MayDesk project.
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. 
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.*/
```

Let me know.

**Comment by chrismay2** [comment]
well observated, for me it is ok like that!
