### ISSUE TITLE
Rewrite Chat Window as client component

### ISSUE THREAD

**Issue by chrismay2** [maydesk/modules#20]
There are several reasons which make a client-side implementation of the Chat Window advisable:
- When I hit Enter it takes a second or so till the text field is cleared and the text is moved to the chat history. Instead, this should happen instantly (without server roundtrip)
- The chat history does not scroll down to the newest message. This is not feasable with the current ContainerEx component but it would be very important for usability

Other issues with Chat Window:
- Make user image  (of chat partner) smaller - text field get partially hidden otherwise
- When typing and the other user is posting a message at the same time the text disappears

**Comment by kriegerd** [comment]
Chat has been reimplemented. Everything seems to be working smoothly with both the scrollbar issue and the text disappearing issue resolved. 

I didn't make the user image smaller yet. I set the text as a text area and made it the same height as the image. The image would have to be resized on the client so I wanted to test if this worked first.
